version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          COVERAGE: true
          DB_HOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
      - image: cimg/postgres:13.6-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrestest
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          command: bundle
      - run:
          command: bin/rubocop
      - run:
          command: bin/rails db:setup
      - run:
          command: bin/rspec
