mutation($input: CreateNotificationInput!) {
    createNotification(input: $input) {
        clientMutationId
        errors {
          location
          message
        }
        notification { id }
    }
}
